name: Run make under CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          show-progress: false
      - name: install ruff
        run: |
          sudo apt-get update
          sudo apt-get -y install pipx
          sudo pipx install ruff
          sudo pip install mypy
      - name: Install shellcheck and checkbashisms
        run: sudo apt install shfmt shellcheck devscripts
      - name: Install markdownlint
        run: npm install markdownlint-cli2 --global
      - name: style check
        run: make style-check
